language: c
dist: trusty

matrix:
    include:
        - os: linux
          env: BUILD=x86_64-linux-gnu

        - os: linux
          compiler: clang

        - os: linux
          env: BUILD=i686-linux-gnu CFLAGS=-m32
          addons:
              apt:
                  packages:
                      - gcc-multilib

        - os: osx

script:
    - ./bootstrap && ./configure && make
    - file src/openocd
